/** Shapes of the data generated by `npm run data:build` from the Quranic Arabic Corpus. */

export type CorpusPos = 'N' | 'V' | 'P';

export interface Segment {
	text: string;
	pos: CorpusPos;
	lemma?: string;
	root?: string;
	/** Raw corpus feature tags, e.g. `DET`, `PREF`, `GEN`, `ACT_PCPL`. */
	tags: string[];
}

export interface Word {
	/** 1-based position of the word within its verse. */
	n: number;
	text: string;
	gloss: string;
	/** Set when the word is an inflected form of a vocabulary card. */
	lexemeId?: string;
	segments: Segment[];
}

export interface Verse {
	surah: number;
	ayah: number;
	words: Word[];
}

export interface Lexeme {
	id: string;
	/** Dictionary form (lemma), with vowel marks. */
	arabic: string;
	/** Three-letter root without separators, e.g. `رحم`. */
	root?: string;
	pos: 'noun' | 'verb' | 'particle';
	gloss: string;
	/** Occurrences of this lemma in the Quran. */
	count: number;
	/** 1 = most frequent lemma in the Quran. */
	rank: number;
	/** One real occurrence, shown as "seen in". */
	sample: { loc: string; form: string };
}

export interface FatihaData {
	source: string;
	verses: Verse[];
}

export interface LexiconData {
	source: string;
	lexemes: Lexeme[];
}
