/** Shapes of the data generated by `npm run data:build` from the Quranic Arabic Corpus. */

export type CorpusPos = 'N' | 'V' | 'P';

/**
 * One piece of a word: a prefix, the stem or an ending. Only what the app displays is kept, to
 * keep the download small: the text and the tags `DET` (the article), `PREF`, `SUFF` and `PRON`.
 */
export interface Segment {
	text: string;
	tags: string[];
}

export interface Word {
	/** 1-based position of the word within its verse. */
	n: number;
	text: string;
	gloss: string;
	/** Set when the word is an inflected form of a vocabulary card. */
	lexemeId?: string;
	/** The word's pieces. Left out for a word that is a single piece; use `segmentsOf`. */
	segments?: Segment[];
}

export interface Verse {
	surah: number;
	ayah: number;
	words: Word[];
}

export interface Lexeme {
	id: string;
	/** Dictionary form (lemma), with vowel marks. */
	arabic: string;
	/** Three-letter root without separators, e.g. `رحم`. */
	root?: string;
	pos: 'noun' | 'verb' | 'particle';
	gloss: string;
	/** Occurrences of this lemma in the Quran. */
	count: number;
	/** 1 = most frequent lemma in the Quran. */
	rank: number;
	/** One real occurrence, shown as "seen in". */
	sample: { loc: string; form: string };
}

export interface VerseData {
	source: string;
	verses: Verse[];
}

export interface LexiconData {
	source: string;
	lexemes: Lexeme[];
}
